---
- name: Ensure skype user is enabled
  user: name=skype shell=/sbin/nologin

- name: Ensure Skype binary is downloaded
  get_url: url=http://download.skype.com/linux/skype-{{ skype_version }}.tar.bz2 dest=/tmp/

- name: Ensure tarball is extracted
  shell: creates={{ skype_install_dir }}-{{ skype_version }} tar jxf /tmp/skype-{{ skype_version }}.tar.bz2 -C /opt/

- name: Ensure symbolix link is present
  file: path={{ skype_install_dir }} src={{ skype_install_dir }}-{{ skype_version }} state=link

- name: Ensure symbolix link is present
  file: path=/usr/share/skype src={{ skype_install_dir }} state=link

- name: Ensure symbolix link is present
  file: path=/usr/bin/skype src={{ skype_install_dir }}/skype state=link

- name: Ensure dependencies are installed
  yum: name={{ item }} state=installed
  with_items:
    - glibc.i686 
    - nss-softokn-freebl.i686 
    - alsa-lib.i686 
    - libXv.i686
    - libXScrnSaver.i686 
    - libtiff.i686 
    - libSM.i686 
    - libXrender.i686 
    - fontconfig.i686
    - pulseaudio-libs.i686 
    - alsa-plugins-pulseaudio.i686 
    - libQtDBus.so.4 
    - libQtWebKit.so.4
    - Xvfb 
    - python-devel
    - python-setuptools
    - libselinux-python
    - x11vnc
    - ipa-gothic-fonts

- name: Ensure pip is installed
  easy_install: name=pip

- name: Ensure Skype4Py is installed
  pip: name=Skype4Py

- name: Ensure init script is present
  shell: creates={{ skype_init_script }} curl -L -o {{ skype_init_script }} https://gist.githubusercontent.com/shufo/70d8ca05305f8848196b/raw/144870dda3a3fe320563c732d4b846c5e17297cb/skype

- name: Ensure init script is executable
  file: path={{ skype_init_script }} mode=0755

- name: Ensure skype directories is present
  file: path={{ item }} state=directory owner=skype group=skype
  with_items:
    - /var/db/skype
    - /var/run/skype
    - /var/log/skype

- name: Ensure selinux is disabled
  selinux: state=disabled

- name: Ensure dbus uuid is generated
  shell: creates=/var/lib/dbus/machine-id dbus-uuidgen > /var/lib/dbus/machine-id

- name: Ensure Skype username is set
  lineinfile: dest={{ skype_init_script }} regexp=^USERNAME= line=USERNAME={{ skype_username }}

- name: Ensure Skype password is set
  lineinfile: dest={{ skype_init_script }} regexp=^PASSWORD= line=PASSWORD={{ skype_password }}

- name: Ensure Skype is started
  service: name=skype state=started enabled=yes

- name: Ensure hubot dependencies are instaled
  yum: name={{ item }} state=installed
  with_items:
    - npm
    - redis

- name: Ensure hubot dependencies are instaled
  npm: name={{ item }} global=yes
  with_items:
    - hubot 
    - coffee-script 
    - yo 
    - generator-hubot

- name: Ensure hubot is installed
  copy: src=files/hubot/ dest={{ hubot_install_dir }} owner=skype group=skype

- name: Ensure hubot node_modules is installed
  npm: path={{ hubot_install_dir }}

- name: Ensure hubot script is executable
  file: path={{ hubot_install_dir }}/bin/hubot mode=0755

- name: Ensure supervisord is installed
  pip: name=supervisor

- name: Ensure supervisord conf is set
  shell: creates=/etc/supervisord.conf echo_supervisord_conf > /etc/supervisord.conf

- name: Ensure supervisord include dir is present
  file: path=/etc/supervisord.d state=directory

- name: Ensure include statement is enabled
  lineinfile: dest=/etc/supervisord.conf line=[include]

- name: Ensure include statement is enabled
  lineinfile: dest=/etc/supervisord.conf insertafter=\[include\] line="files=supervisord.d/*.conf"

- name: Ensure hubot supervisord conf is set
  template: src=templates/supervisord_hubot.conf.j2 dest=/etc/supervisord.d/hubot.conf

- name: Ensure x11vnc supervisord conf is set
  template: src=templates/supervisord_x11vnc.conf.j2 dest=/etc/supervisord.d/x11vnc.conf

- name: Ensure supervisord upstart file is set
  template: src=templates/supervisord_upstart.conf.j2 dest=/etc/init/supervisord.conf

- name: Ensure supervisord is started
  shell: creates=/tmp/supervisor.sock start supervisord

- name: X11vnc is started
  shell: /usr/bin/x11vnc -display :20 -xauth /var/run/skype/Xauthority -bg

- name: output finish message
  debug: msg="Install Finished! Please connect your VNC viewer to port 5900 on target host, and accept Skype public API access(check remember)."
