---
- include: supervisord.yml
- include: skype.yml
- include: hubot.yml

- name: Ensure supervisord is started
  shell: creates=/tmp/supervisor.sock start supervisord

- name: output finish message
  debug: msg="Install Finished! Please connect your VNC viewer to port 5900 on target host, and accept Skype public API access(check remember)."
